In [74]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns

## question 1

In [75]:
pd.__version__

'3.0.6'

## data pull

In [76]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## question 2

In [77]:
df.shape

(10000, 11)

## question 3

In [78]:
df['fuel_type'].nunique()

3

## question 4

In [79]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## question 5

In [80]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

## question 6

In [81]:
series = df['horsepower']
median_h = int(series.median())
mode_h = int(series.mode().iloc[0])
print(f'median: {median_h} mode: {mode_h}')

median: 254 mode: 252

In [82]:
series = series.fillna(mode_h)

In [83]:
median_h2 = series.median()
median_h2

np.float64(252.0)

## question 7

In [84]:
short_df = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)
short_df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [85]:
# underlying numpy array
X = np.array(short_df)
X, X.T

(array([[4240, 1996],
        [4310, 1992],
        [4230, 1997],
        [4420, 1978],
        [3950, 2007],
        [4750, 2021],
        [4450, 2019]]),
 array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
        [1996, 1992, 1997, 1978, 2007, 2021, 2019]]))

In [86]:
X.shape, X.T.shape

((7, 2), (2, 7))

In [87]:
# transpose of X times X (dot product)
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [88]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [89]:
# get the inverse of XTX
z =np.linalg.inv(XTX)
z

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [90]:
#  multiply the inverse of XTX with X.T then multiply by y
product = z.dot(X.T).dot(y)
product

array([0.13644777, 0.2327492 ])

In [91]:
sum(product)

np.float64(0.36919696904925486)