In [ ]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns

## question 1

In [ ]:
pd.__version__

'2.1.4'

## data pull

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## question 2

In [ ]:
df.shape

(10000, 11)

## question 3

In [ ]:
df['fuel_type'].nunique()

3

## question 4

In [ ]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## question 5

In [ ]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

41.2

## question 6

In [ ]:
series = df['horsepower']
median_h = int(series.median())
mode_h = int(series.mode())
print(f'median: {median_h} mode: {mode_h}')

median: 254 mode: 252

/var/folders/fw/d4zbz2s53fv_w10z_gmy48mr0000gn/T/ipykernel_45325/1652315378.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  mode_h = int(series.mode())

In [ ]:
series = series.fillna(mode_h)

In [ ]:
median_h2 = series.median()
median_h2

252.0

## question 7

In [ ]:
short_df = df[['vehicle_weight', 'model_year']].head(7)
short_df

   vehicle_weight  model_year
0            3870        2006
1            4210        2008
2            4240        1996
3            4490        1989
4            4510        1994
5            4260        2007
6            4310        1992